### ISSUE TITLE
Yosemite Python 3.4 swizzle getattr() attribute name must be string

### ISSUE THREAD

**Issue by temoto** [dbader/pytest-osxnotify#6]
Hello. Please tell if I can fix this with some quick patch.

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/_pytest/main.py", line 82, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/pytest_osxnotify/__init__.py", line 27, in pytest_sessionstart
INTERNALERROR>     notify('py.test', 'Running tests...')
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/pytest_osxnotify/__init__.py", line 78, in notify
INTERNALERROR>     swizzled_bundleIdentifier)
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/pytest_osxnotify/__init__.py", line 52, in swizzle
INTERNALERROR>     old_IMP = getattr(cls, SEL, None)
INTERNALERROR> TypeError: getattr(): attribute name must be string

% uname -a
Darwin leebook 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64

% venv/bin/python --version
Python 3.4.3

% venv/bin/pip freeze
py==1.4.26
pyobjc-core==3.0.4
pytest==2.6.4
pytest-osxnotify==0.1.5   # master ce865a7536abdf67f4b6dec8aa5952ce4f707dc2
```

**Comment by temoto** [comment]
Found that it fails with `SEL=b'bundleIdentifier'`.
Fix attempt:
```
old_IMP = getattr(cls, str(SEL), None)
```
new error:
```
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/pytest_osxnotify/__init__.py", line 27, in pytest_sessionstart
INTERNALERROR>     notify('py.test', 'Running tests...')
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/pytest_osxnotify/__init__.py", line 78, in notify
INTERNALERROR>     swizzled_bundleIdentifier)
INTERNALERROR>   File "/.../venv/lib/python3.4/site-packages/pytest_osxnotify/__init__.py", line 55, in swizzle
INTERNALERROR>     old_IMP = cls.instanceMethodForSelector_(SEL)
INTERNALERROR> AttributeError: No selector bundleIdentifier
```

**Comment by dbader** [comment]
Fixed in https://pypi.python.org/pypi/pytest-osxnotify/0.1.6
Thanks @temoto!
